name: Deploy to InfinityFree

on:
  push:
    branches:
      - main
      - master

jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Sync files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          # The local directory to deploy from. In this case, the project is inside event-management-system/
          local-dir: ./event-management-system/
          # The directory on the remote server to deploy to. 
          # InfinityFree usually requires files inside htdocs/
          server-dir: htdocs/
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
            .github/**
